# Generated by Django 4.2.7 on 2023-12-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_positionhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positionhistory',
            old_name='price',
            new_name='price_per_share',
        ),
    ]
