# Generated by Django 4.2.7 on 2023-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_rename_price_positionhistory_price_per_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionhistory',
            name='date_added',
            field=models.DateField(blank=True, null=True),
        ),
    ]
